### PR TITLE
SYNC: Synched with Luis upstream repo, resolving conflicts

### PR DESCRIPTION
**Pull request by Nurassyl-lab**
`python mlm_training.py -v` run fine with `sys.exit()` in line 402

### CODE REVIEW

**Comment by ottersome** [comment]
Introduce stylistic changes in your own commits if you want them. Or just turn off you formatter in VS code.

**Comment by ottersome** [comment]
Also, [ec63884](https://github.com/ottersome/MultiHopKG/pull/3/commits/ec638846349c31c07b90cac80f8d13afc5743629) is duplicate of prexisting 5cc14b2a13da12be605a108dff03accec3ecdc27 and therefore cannot rebase. Either rebase your changes into current maste of this repo or figure something out with chatgpt that accomplishes the same thing.

**Comment by Nurassyl-lab** [comment]
noted, that's a formatter....

**Comment by Nurassyl-lab** [comment]
about the pre-existing commits, when we merge `mlm_training.py`, it has all of those conflicts... 
anyways will fix em b4 tomorrow :0

**Comment by ottersome** [comment]
> about the pre-existing commits, when we merge `mlm_training.py`, it has all of those conflicts... anyways will fix em b4 tomorrow :0

If you guys can't make it you can still push your WIP into your own fork and I'll fix it. Just ping me please.  Remember that now  while you guys sleep I work and vice-versa.

**Pull request closed without merging**
